name: 'action-cmake'
description: 'Build and test a CMake based project on multiple platforms.'
author: 'brinkqiang'
inputs: 
  build_type:
    description: "cmake BUILD_TYPE"
    required: true
    default: "relwithdebinfo"
branding:
  icon: 'chevron-up'
  color: 'red'

runs:
  using: 'action-cmake task runner'
  steps:
    - name: setup-windows
      if: runner.os == 'Windows'
      shell: bash
      run: ${GITHUB_ACTION_PATH}/setup.bat

    - name: setup-Posix
      if: runner.os != 'Windows'
      shell: bash
      run: ${GITHUB_ACTION_PATH}/setup.sh  
    - uses: actions/checkout@v2
    - uses: lukka/get-cmake@latest

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H%M')"

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config ${{env.BUILD_TYPE}}

    - name: Test
      shell: bash
      run: ctest -C ${{env.BUILD_TYPE}}


    - name: Status
      uses: Sibz/github-status-action@v1

      with:
        authToken: ${{secrets.GITHUB_TOKEN}}
        context: 'Set Status'
        description: 'Passed'
        state: 'success'
